# Generated by Django 3.2 on 2022-07-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_auto_20220627_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillistupload',
            name='cloud_created_at',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='emaillistupload',
            name='file_format',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='emaillistupload',
            name='file_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='emaillistupload',
            name='public_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='emaillistupload',
            name='tags',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
