UPLOAD_PROCESSING_STATUS = "Processing"
UPLOAD_COMPLETED_STATUS = "Completed"
UPLOAD_FAILED_STATUS = "Failed"

UPLOAD_STATUSES = (
    (UPLOAD_PROCESSING_STATUS, UPLOAD_PROCESSING_STATUS),
    (UPLOAD_COMPLETED_STATUS, UPLOAD_COMPLETED_STATUS),
    (UPLOAD_FAILED_STATUS, UPLOAD_FAILED_STATUS)
)




EMAIL_RECIPIENT_SUCCESS_STATUS = "Completed"
EMAIL_RECIPIENT_FAILED_STATUS = "Failed"